config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :products, only: [:new, :create, :index]
  root to: 'products#index'

  get "cart", to: "orders#cart"
  post "add_item", to: "orders#add_item_to_cart", as: :add_item_to_cart
  delete "remove_item", to: "orders#remove_item_from_cart", as: :remove_item_from_cart
  put "finish_order", to: "orders#finish_order", as: :finish_order

  get "my_purchases", to: "orders#my_purchases"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :items, class_name: "OrderItem"

  scope :cart, -> { where(paid_at: nil) }
  scope :finished, -> { where.not(paid_at: nil) }

  def total
    items.sum(:price)
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, :price, presence: true

  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders

  def cart
    orders.cart.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :redirect_user_without_session

  def cart
    @cart = current_user.cart
  end

  def my_purchases
    @orders = current_user.orders.finished.order(paid_at: :desc)
  end

  def add_item_to_cart
    cart = current_user.cart || Order.create(user: current_user)

    product = Product.find_by(id: params[:product_id])

    item = OrderItem.new(order: cart, product: product, price: product.price)

    if item.save
      redirect_to cart_path
    else
      head 404
    end
  end

  def remove_item_from_cart
    item = OrderItem.find_by(id: params[:item_id])

    if item.destroy
      redirect_to cart_path
    else
      head 404
    end
  end

  def finish_order
    order = Order.find_by(id: params[:order_id])

    if order.update(paid_at: Time.new)
      redirect_to root_path
    else
      head 404
    end
  end

  private

  def redirect_user_without_session
    redirect_to new_user_session_path if current_user.blank?
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(form_params)

    if @product.save
      redirect_to new_product_path
    else
      render :new
    end
  end

  private

  def form_params
    params.require(:product).permit(:name, :price, :image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<nav style="background-color:#ffd500!important" class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <a class="navbar-brand" href="/"><i><b>Electroplace</b></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <% if current_user.present? %>
          <li class="nav-item active">
            <a class="nav-link" href="/my_purchases">Minhas compras</a>
          </li>
        <% end %>
      </ul>
      <ul class="navbar-nav ml-auto">
        <% if current_user.present? %>
          <li class="nav-item active">
            <a class="nav-link" href="#"><%= current_user.email %></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/cart"><i class="fa fa-shopping-cart"></i></a>
          </li>
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Electroplace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/orders/cart.html.erb
<div class="container">

  <% if @cart.blank? || @cart.items.none? %>

    <h2 class="mt-5">Ainda nao há itens no seu Carrinho</h2>

  <% else %>
    <h2 class="mt-5">Carrinho</h2>

    <% @cart.items.each do |item| %>

      <div class="card mt-3 mb-3">
        <div class="card-body">
          <div class="row">
            <div class="col-10">
              <%= image_tag(item.product.image, style: "width: 150px; height: 150px; object-fit: contain;") %>
            </div>
            <div class="col-2">
              <h4><%= item.product.name %></h4>
              <h4>R$ <%= item.price %></h4>
              <%= link_to "Remover Item", remove_item_from_cart_path(item_id: item.id), method: :delete, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
      </div>

    <% end %>

    <div class="text-right mt-4">
      <h4>Total: <span style="color: green;">R$ <%= @cart.total %></span></h4><br>
      <%= link_to "Finalizar Pedido", finish_order_path(order_id: @cart.id), method: :put, class: "btn btn-info" %>
    </div>

    <% end %>
</div>

app/views/orders/my_purchases.html.erb
<div class="container">
  <h2 class="mt-5">Minhas Compras</h2>

  <% @orders.each do |order| %>
  <div class="card mt-3 mb-3">
    <div class="card-header">
      <h6>Total: R$ <%= order.total %></h6>
      <h6>Finalizado em: <%= order.paid_at.strftime("%d/%m/%Y %H:%M") %></h6>
    </div>
    <div class="card-body">

      <% order.items.each do |item| %>
        <div class="row">
          <div class="col-2">
            <%= image_tag(item.product.image, style: "width: 75px; height: 75px; object-fit: contain;") %>
          </div>
          <div class="col-10">
            <h6><%= item.product.name %></h6>
            <h6>R$ <%= item.price %></h6>
          </div>
        </div>
      <% end %>

      </div>
    </div>

  <% end %>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row mt-5">
    <% @products.each do |product| %>
      <div class="d-flex col-4">
        <div class="card mt-5" style="width: 18rem;">
          <%= image_tag(product.image, style: "max-height: 200px; object-fit: contain;") %>
          <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
          </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">R$ <%= product.price %></li>
          </ul>
          <div class="card-body text-center">
            <%= link_to "Adicionar ao carrinho", add_item_to_cart_path(product_id: product.id), method: :post, class: "btn btn-success" %>
          </div>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <div class="offset-4 col-4 mt-5">
    <div class="card">
      <div class="card-body">
        <%= form_with(model: @product, url: products_path, local: true) do |f| %>

        <% if @product && @product.errors.any? %>
          <ul>
            <% @product.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
          <div class="form-group">
            <%= f.label "Nome" %><br />
            <%= f.text_field :name, autofocus: true, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label "Preço" %><br />
            <%= f.number_field :price, step: 0.01, min: 0, class: "form-control" %>
          </div>

          <div class="form-group">
            <%= f.label "Imagem" %><br />
            <%= f.file_field(:image) %>
          </div>

          <div class="text-center"><button type="submit" class="btn btn-primary">Criar produto</button></div>
        <% end %>
      </div>
    </div>
  </div>
</div>